CREATE TABLE PRODUCTS (
PRODUCT_ID NUMBER,
CONSTRAINT PRODUCTS_PK PRIMARY KEY (PRODUCT_ID),
PRODUCT_NAME NVARCHAR2(100),
SUPPLIER_ID NUMBER,
CONSTRAINT SUPPLIERS_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS (SUPPLIER_ID),
CATEGORY_ID NUMBER,
CONSTRAINT CATEGORIES_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (CATEGORY_ID),
QUANTITY_PER_UNIT NUMBER,
UNIT_PRICE NUMBER(8,2),
UNITS_IN_STOCK NUMBER,
UNITS_ON_ORDER NUMBER,
RECORDER_LEVEL NVARCHAR2(50),
DISCONTINUED NUMBER(8,2)
);