CREATE TABLE CUSTOMER (
CUSTOMER_ID NUMBER PRIMARY KEY,
CUSTNAME NVARCHAR2(50) NOT NULL,
CITY NVARCHAR2(50) NOT NULL,
SALESMAN_ID NUMBER,
CONSTRAINT SALESMAN_FK FOREIGN KEY (SALESMAN_ID) REFERENCES SALESMAN (SALESMAN_ID)
);

INSERT INTO CUSTOMER VALUES (3002, 'Nick Rimando', 'New York', 5001);
INSERT INTO CUSTOMER VALUES (3005, 'Graham Zusi', 'California', 5002);
INSERT INTO CUSTOMER VALUES (3001, 'Brad Guzan', 'London', 5005);
INSERT INTO CUSTOMER VALUES (3004, 'Fabian Johns', 'Paris', 5006);
INSERT INTO CUSTOMER VALUES (3009, 'Geof Camero', 'Berlin', 5003);
INSERT INTO CUSTOMER VALUES (3008, 'Julian Green', 'London', 5002);
INSERT INTO CUSTOMER VALUES (3007, 'Brad Davis', 'New York', 5001);
INSERT INTO CUSTOMER VALUES (3003, 'Jozy Altido', 'Moscow', 5007);
INSERT INTO CUSTOMER VALUES (3010, 'Misha Test', 'Kiev', null);