CREATE TABLE SALESMAN (
SALESMAN_ID NUMBER PRIMARY KEY,
NAME NVARCHAR2(50) NOT NULL,
CITY NVARCHAR2(50) NOT NULL,
COMMISSION NUMBER(*,2) DEFAULT 0.1
);

INSERT INTO SALESMAN VALUES (5001, 'James Hoog', 'New York', 0.15);
INSERT INTO SALESMAN VALUES (5002, 'Nail Knite', 'Paris', 0.13);
INSERT INTO SALESMAN VALUES (5005, 'Pit Alex', 'London', 0.11);
INSERT INTO SALESMAN VALUES (5006, 'Mc Lyon', 'Paris', 0.14);
INSERT INTO SALESMAN VALUES (5003, 'Lauson Hen', 'London', 0.12);
INSERT INTO SALESMAN VALUES (5007, 'Andrew Wise', 'Nikosia', 0.29);
INSERT INTO SALESMAN VALUES (5008, 'Some Salesman', 'Kiev', 0.09);
INSERT INTO SALESMAN VALUES (5009, 'Denis Kokorin', 'Moskow', 0.1);