CREATE TABLE ORDERS1 (
ID NUMBER,
CONSTRAINT ID_PK PRIMARY KEY (ID),
USER_ID NUMBER,
ROOM_ID NUMBER,
DATE_FROM TIMESTAMP,
DATE_TO TIMESTAMP,
MONEY_PAID NUMBER(8,2),
CONSTRAINT CHECK_ID CHECK (ID < 10000)
);