CREATE TABLE FORUM_POSTS (
ID INT NOT NULL,
CONSTRAINT FORUM_POSTS_PK PRIMARY KEY (ID),
ID_SUBCATEGORY INT NOT NULL,
CONSTRAINT FORUM_SUBCATEGORIES_FK FOREIGN KEY (ID_SUBCATEGORY) REFERENCES FORUM_SUBCATEGORIES (ID),
ID_USER INT NOT NULL,
CONSTRAINT USERS_FK FOREIGN KEY (ID_USER) REFERENCES USERS (ID),
PARENT_POST INT NOT NULL,
TITLE VARCHAR(90),
CONTENT CLOB NOT NULL,
IS_POLL NUMBER(1) DEFAULT 0 NOT NULL,
DATE_LOADED TIMESTAMP NOT NULL,
IP VARCHAR(20) NOT NULL
);