CREATE TABLE FORUM_CATEGORIES (
ID INT NOT NULL,
CONSTRAINT FORUM_CATEGORIES_PK PRIMARY KEY (ID),
TITLE VARCHAR(64) NOT NULL,
DESCRIPTION VARCHAR(1000) NOT NULL,
DATE_CREATE_CATEGORY TIMESTAMP NOT NULL,
IP VARCHAR(20) NOT NULL
);