CREATE TABLE ORDER_DETAILS (
ORDER_ID NUMBER,
CONSTRAINT ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
PRODUCT_ID NUMBER,
CONSTRAINT PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
CONSTRAINT ORDER_DETAILS_PK PRIMARY KEY (ORDER_ID, PRODUCT_ID),
UNIT_PRICE NUMBER(8,2),
QUANTITY NUMBER,
DISCOUNT NUMBER(8,2)
);