CREATE TABLE ORDER_DETAILS (
ORDER_ID NUMBER,
CONSTRAINT ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
PRODUCT_ID NUMBER,
CONSTRAINT PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
UNIT_PRICE NUMBER(8,2),
CONSTRAINT PRODUCTS FOREIGN KEY (UNIT_PRICE) REFERENCES PRODUCTS(UNIT_PRICE),
QUANTITY NUMBER,
CONSTRAINT PRODUCTS FOREIGN KEY (QUANTITY) REFERENCES PRODUCTS(QUANTITY_PER_UNIT),
DISCOUNT NUMBER(8,2),
CONSTRAINT PRODUCTS FOREIGN KEY (DISCOUNT) REFERENCES PRODUCTS(DISCONTINUED)
);