CREATE TABLE FORUM_SUBCATEGORIES (
ID INT NOT NULL,
CONSTRAINT FORUM_SUBCATEGORIES_PK PRIMARY KEY (ID),
ID_CATEGORY INT NOT NULL,
CONSTRAINT FORUM_CATEGORIES_FK FOREIGN KEY (ID_CATEGORY) REFERENCES FORUM_CATEGORIES (ID),
TITLE VARCHAR(45) NOT NULL,
DESCRIPTION VARCHAR(1000) NOT NULL,
DATE_SUBCAT TIMESTAMP NOT NULL,
IP VARCHAR(20) NOT NULL
);