CREATE TABLE USERS (
ID INT NOT NULL,
CONSTRAINT USERS_PK PRIMARY KEY (ID),
NICK VARCHAR(64) NOT NULL,
PASSWORD VARCHAR(128) NOT NULL,
EMAIL VARCHAR(128) NOT NULL,
DATE_LOGIN TIMESTAMP NOT NULL,
KARMA NUMBER(8,2) NOT NULL,
IP VARCHAR(20) NOT NULL
);