CREATE TABLE MOVIE (
ID NUMBER,
CONSTRAINT MOVIE_ID PRIMARY KEY (ID),
TITLE NVARCHAR2(50) NOT NULL,
DIRECTOR NVARCHAR2(50) NOT NULL,
YEAR NUMBER(4) CHECK (YEAR > 1899 AND YEAR < 2019),
LENGTH_MINS NUMBER CHECK (LENGTH_MINS > 9 AND LENGTH_MINS < 201)
);