CREATE TABLE HOTEL (
ID NUMBER,
CONSTRAINT ID_HPK PRIMARY KEY (ID),
COUNTRY NVARCHAR2(50) DEFAULT 'N/A' CHECK (COUNTRY != 'Romania' AND COUNTRY != 'Belgium' AND COUNTRY != 'China' AND
    COUNTRY != 'Ukraine'),
CITY NVARCHAR2(50) NOT NULL,
STREET NVARCHAR2(50)
);

DROP TABLE HOTEL;

INSERT INTO HOTEL
VALUES (10001, 'RUSSIA', 'MOSCOW', 'RRRRRRRRRRRRRRRR');

INSERT INTO HOTEL
VALUES (10002, 'Ukraine', 'MOSCOW', 'RRRRRRRRRRRRRRRR');

INSERT INTO HOTEL
VALUES (10003, 'China', 'MOSCOW', 'RRRRRRRRRRRRRRRR');

INSERT INTO HOTEL
VALUES (10001, 'RUSSIA', NULL, 'RRRRRRRRRRRRRRRR');